[2024-04-26T13:15:08.058+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2024-04-26T13:15:07.421490+00:00 [queued]>
[2024-04-26T13:15:08.066+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2024-04-26T13:15:07.421490+00:00 [queued]>
[2024-04-26T13:15:08.067+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-04-26T13:15:08.078+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2024-04-26 13:15:07.421490+00:00
[2024-04-26T13:15:08.082+0000] {standard_task_runner.py:57} INFO - Started process 839 to run task
[2024-04-26T13:15:08.086+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2024-04-26T13:15:07.421490+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmp_74dpnzv']
[2024-04-26T13:15:08.087+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask load_seed_data_once
[2024-04-26T13:15:08.141+0000] {task_command.py:410} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2024-04-26T13:15:07.421490+00:00 [running]> on host 511926b065ed
[2024-04-26T13:15:08.248+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='1_init_once_seed_data' AIRFLOW_CTX_TASK_ID='load_seed_data_once' AIRFLOW_CTX_EXECUTION_DATE='2024-04-26T13:15:07.421490+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-26T13:15:07.421490+00:00'
[2024-04-26T13:15:08.249+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-26T13:15:08.250+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2024-04-26T13:15:08.260+0000] {subprocess.py:86} INFO - Output:
[2024-04-26T13:15:10.204+0000] {subprocess.py:93} INFO - [0m13:15:10  Running with dbt=1.5.2
[2024-04-26T13:15:11.421+0000] {subprocess.py:93} INFO - [0m13:15:11  Registered adapter: snowflake=1.5.1
[2024-04-26T13:15:11.424+0000] {subprocess.py:93} INFO - [0m13:15:11  Encountered an error:
[2024-04-26T13:15:11.425+0000] {subprocess.py:93} INFO - Compilation Error
[2024-04-26T13:15:11.425+0000] {subprocess.py:93} INFO -   dbt found 1 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
[2024-04-26T13:15:12.162+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-26T13:15:12.175+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-26T13:15:12.179+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20240426T131507, start_date=20240426T131508, end_date=20240426T131512
[2024-04-26T13:15:12.192+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 65 for task load_seed_data_once (Bash command failed. The command returned a non-zero exit code 2.; 839)
[2024-04-26T13:15:12.248+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-04-26T13:15:12.265+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
