[2023-07-09T07:03:56.291+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-07-09T07:03:55.361926+00:00 [queued]>
[2023-07-09T07:03:56.297+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-07-09T07:03:55.361926+00:00 [queued]>
[2023-07-09T07:03:56.298+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-09T07:03:56.307+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-07-09 07:03:55.361926+00:00
[2023-07-09T07:03:56.311+0000] {standard_task_runner.py:57} INFO - Started process 114 to run task
[2023-07-09T07:03:56.314+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2023-07-09T07:03:55.361926+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmp7pokq4s7']
[2023-07-09T07:03:56.315+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask load_seed_data_once
[2023-07-09T07:03:56.357+0000] {task_command.py:410} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-07-09T07:03:55.361926+00:00 [running]> on host bb7f693c3816
[2023-07-09T07:03:56.443+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='1_init_once_seed_data' AIRFLOW_CTX_TASK_ID='load_seed_data_once' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T07:03:55.361926+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-09T07:03:55.361926+00:00'
[2023-07-09T07:03:56.444+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-09T07:03:56.445+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/dbt && dbt seed --profiles-dir .']
[2023-07-09T07:03:56.453+0000] {subprocess.py:86} INFO - Output:
[2023-07-09T07:03:57.885+0000] {subprocess.py:93} INFO - [0m07:03:57  Running with dbt=1.5.2
[2023-07-09T07:03:58.748+0000] {subprocess.py:93} INFO - [0m07:03:58  Registered adapter: snowflake=1.5.1
[2023-07-09T07:03:58.782+0000] {subprocess.py:93} INFO - [0m07:03:58  Unable to do partial parsing because a project config has changed
[2023-07-09T07:03:59.494+0000] {subprocess.py:93} INFO - [0m07:03:59  Encountered an error:
[2023-07-09T07:03:59.495+0000] {subprocess.py:93} INFO - Compilation Error
[2023-07-09T07:03:59.496+0000] {subprocess.py:93} INFO -   Model 'model.poc.combined_bookings' (models/transform/combined_bookings.sql) depends on a node named 'bookings_1' which was not found
[2023-07-09T07:04:00.157+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-07-09T07:04:00.169+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-09T07:04:00.172+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20230709T070355, start_date=20230709T070356, end_date=20230709T070400
[2023-07-09T07:04:00.180+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 43 for task load_seed_data_once (Bash command failed. The command returned a non-zero exit code 2.; 114)
[2023-07-09T07:04:00.222+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-09T07:04:00.244+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
