[0m02:24:58.064117 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104753340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105993a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1059a46a0>]}


============================== 02:24:58.066971 | 84945b34-3cdc-44ab-9e21-ba090f7bece9 ==============================
[0m02:24:58.066971 [info ] [MainThread]: Running with dbt=1.5.2
[0m02:24:58.067338 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/debolbac/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m02:24:58.067642 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/debolbac/.dbt')}
[0m02:24:58.067823 [info ] [MainThread]: Creating dbt configuration folder at 
[0m02:25:58.336330 [debug] [MainThread]: Starter project path: /Users/debolbac/Documents/cassio-git/airflow-dbt-snowflake-poc/dbt_airflow/env/lib/python3.8/site-packages/dbt/include/starter_project
[0m02:31:51.672686 [info ] [MainThread]: Profile dbt_project written to /Users/debolbac/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m02:31:51.673335 [info ] [MainThread]: 
Your new dbt project "dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m02:31:51.673875 [debug] [MainThread]: Command `dbt init` succeeded at 02:31:51.673778 after 413.62 seconds
[0m02:31:51.674157 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104753340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1059d2c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1059a4d60>]}
[0m02:31:51.674462 [debug] [MainThread]: Flushing usage events
[0m02:38:37.294036 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072a9370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ee3ee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ee3250>]}


============================== 02:38:37.298143 | a587af9b-6df1-4232-bdb8-0e0f2b102d7a ==============================
[0m02:38:37.298143 [info ] [MainThread]: Running with dbt=1.5.2
[0m02:38:37.298506 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/debolbac/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m02:38:37.299041 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/debolbac/Documents/cassio-git/airflow-dbt-snowflake-poc/dbt_airflow/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m02:38:37.299495 [debug] [MainThread]: Command `dbt deps` failed at 02:38:37.299391 after 0.02 seconds
[0m02:38:37.299701 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072a9370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ed2d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ed28b0>]}
[0m02:38:37.299899 [debug] [MainThread]: Flushing usage events
[0m10:53:16.009931 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104675340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106da3ee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106da3220>]}


============================== 10:53:16.013282 | 3fbffa25-d17c-4d5a-98eb-bdc7c97e091c ==============================
[0m10:53:16.013282 [info ] [MainThread]: Running with dbt=1.5.2
[0m10:53:16.013667 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/debolbac/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m10:53:16.014213 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/debolbac/Documents/cassio-git/airflow-dbt-snowflake-poc/dbt_airflow/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:53:16.014642 [debug] [MainThread]: Command `dbt deps` failed at 10:53:16.014560 after 0.02 seconds
[0m10:53:16.014829 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104675340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106deb7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106deb8b0>]}
[0m10:53:16.015019 [debug] [MainThread]: Flushing usage events
[0m13:18:44.730953 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff97cdd1d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff97cddf50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff97cdd290>]}


============================== 13:18:44.751022 | 85ce7347-a3c0-4f69-8e16-6f85e07b1c20 ==============================
[0m13:18:44.751022 [info ] [MainThread]: Running with dbt=1.5.2
[0m13:18:44.752435 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/airflow/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m13:18:44.754186 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /opt/airflow/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:18:44.755579 [debug] [MainThread]: Command `dbt deps` failed at 13:18:44.755475 after 0.04 seconds
[0m13:18:44.756748 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff9bfa7e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff97cdda90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff97cddc10>]}
[0m13:18:44.759062 [debug] [MainThread]: Flushing usage events
